In [18]:
import datetime
import pandas as pd

#Create a empty dataframe for combining all csvs
df_list = []

#Define start date and end date, which is the date range of the datasource
start = datetime.date(2021, 1, 1)
end = datetime.date(2023, 3, 9)
res_date = start

#loop each date within the range to extract the csv for the day, and do data cleaning
while res_date <= end:
    #print(res_date)
    #Turn the datetime object into string for url concatenation
    string_date = res_date.strftime("%m-%d-%Y")
    
    #url of github raw content
    url = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/" + string_date + ".csv"
    # print(url)
    
    #Add 1 day to retrieve the next day's data
    res_date += datetime.timedelta(days=1)

#Data cleaning of csv for each day
    #Read csv file, why assign worked?
    df1 = pd.read_csv(url).assign(Date = string_date) #.fillna(0) Since there is no NaN data, fillna function is commented

    df_list.append(df1)

#Concat the csv files together
integrate_df = pd.concat(df_list, ignore_index = True)

#Only select columns that are needed, and extract China only
integrate_df = integrate_df[["Country_Region", "Date","Confirmed","Deaths","Recovered"]]

#Group by country to obtain the overall data of China
integrate_df = integrate_df.groupby(['Country_Region','Date'], as_index = False).agg('sum')

#Drop duplicates
integrate_df.drop_duplicates(subset = ['Date'])
integrate_df.reset_index()
    
integrate_df.head()

  Country_Region        Date  Confirmed  Deaths  Recovered
0    Afghanistan  01-01-2021      52513    2201    41727.0
1    Afghanistan  01-01-2022     158107    7356        0.0
2    Afghanistan  01-01-2023     207616    7849        0.0
3    Afghanistan  01-02-2021      52586    2211    41727.0
4    Afghanistan  01-02-2022     158189    7361        0.0

In [19]:
integrate_df.to_csv("covid_data_worldwide.csv")